require('dotenv').config();

module.exports = {
  development: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    port: Number(process.env.DB_PORT),
    host: process.env.DB_HOST,
    dialect: 'mysql',
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'migrations',
    seederStorage: 'sequelize',
    seederStorageTableName: 'seeds',
  },
  test: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    port: Number(process.env.DB_PORT),
    host: process.env.DB_HOST,
    dialect: 'mysql',
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'migrations',
    seederStorage: 'sequelize',
    seederStorageTableName: 'seeds',
  },
  production: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    port: Number(process.env.DB_PORT),
    host: process.env.DB_HOST,
    dialect: 'mysql',
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'migrations',
    seederStorage: 'sequelize',
    seederStorageTableName: 'seeds',
  },
};
